language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
install:
    - test $TRAVIS_PYTHON_VERSION = "2.6" && pip install argparse || echo
    - pip install . --use-mirrors
script: cd tests && nosetests
